version: "3.7"

x-app: &app
  build:
    context: .
    args:
      precompileassets: 'not'
  depends_on:
    - db
    - kvs
  environment:
    DB_HOST: db
    DB_USER: root
    DB_PASSWORD: ""
    KVS_HOST: kvs
    WEBPACKER_DEV_SERVER_HOST: webpacker
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: access_key
    AWS_SECRET_ACCESS_KEY: secret_key
    BUCKET: development
    MINIO_ENDPOINT: "http://minio:9000"
  volumes:
    - .:/app:cached
    - gem-local:/usr/local/bundle
    - node-local:/app/node_modules
    - app-tmp-local:/app/tmp

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-local:/var/lib/mysql
  kvs:
    image: redis:6
    volumes:
      - kvs-local:/data
  minio:
    image: minio/minio
    environment:
      MINIO_REGION_NAME: ap-northeast-1
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    volumes:
      - minio-data-local:/data
      - minio-config-local:/root/.minio
    ports:
      - "9000:9000"
    command: server /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 access_key secret_key) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --region ap-northeast-1 myminio/development;
      exit 0;
      "
  web:
    <<: *app
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - webpacker
  webpacker:
    <<: *app
    expose:
      - "3035"
    ports:
      - "3035:3035"
    command: bin/webpack-dev-server
  worker:
    <<: *app
    depends_on:
      - web
    command: bundle exec sidekiq

volumes:
  gem-local:
    driver: "local"
  node-local:
    driver: "local"
  db-local:
    driver: "local"
  kvs-local:
    driver: "local"
  minio-data-local:
    driver: "local"
  minio-config-local:
    driver: "local"
  app-tmp-local:
    driver: "local"
